apiVersion: batch/v1
kind: Job
metadata:
  name: load-db
  namespace: titanic
spec:
  ttlSecondsAfterFinished: 300
  completions: 1
  template:
    spec:
      containers:
      - name: loader
        image: [db-fill image] ##Make sure to replace this with your image created from the db-fill folder
        env:
        - name: USERNAME
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: user            
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secrets
              key: password
        - name: DATABASE
          valueFrom:
            configMapKeyRef: 
              name: api-variables
              key: database
        - name: MASTER
          valueFrom:
            configMapKeyRef:
              name: api-variables
              key: writes
      restartPolicy: OnFailure
